/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with a username and password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user and their role */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether Spillway's dependencies are reachable */
        get: operations["status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every key with its limits and this month's spend. Never the key itself. */
        get: operations["listKeys"];
        put?: never;
        /** Create a key. The full key is in the response once and can never be shown again. */
        post: operations["createKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a key. The gateway rejects it from the next request. Revoking twice changes nothing. */
        delete: operations["revokeKey"];
        options?: never;
        head?: never;
        /** Change a key's name, limits or cache settings. A field left out is unchanged; null removes a limit. */
        patch: operations["updateKey"];
        trace?: never;
    };
    "/admin/usage/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Totals, cache outcomes, provider health and a breakdown by day, model or key for a range of UTC days */
        get: operations["usageSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/usage/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The request log, newest first, with the attempts each request made */
        get: operations["usageRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/usage/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One CSV row per day, key and model, with exact dollar amounts */
        get: operations["usageExport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The model catalog and routing policies (read only) */
        get: operations["listModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/playground": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The playground's policies, its key's budget and whether fault injection is on */
        get: operations["playgroundState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/playground/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send one prompt through the gateway under the playground key, optionally making providers fail on purpose
         * @description Admin only, because it spends money. A prompt no provider could answer is still a 200, with `outcome` and
         *     `error` set and the failed route in `attempts`. 402 means the playground key's budget is used up and 429
         *     that its rate limit was hit.
         */
        post: operations["playgroundChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/playground/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Past playground requests, newest first */
        get: operations["playgroundHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Role: "admin" | "viewer";
        LoginRequest: {
            username: string;
            password: string;
        };
        User: {
            username: string;
            role: components["schemas"]["Role"];
        };
        LoginResponse: {
            token: string;
            /** Format: date-time */
            expires_at: string;
            user: components["schemas"]["User"];
        };
        ApiKey: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description The first characters of the key, for recognising it. Never enough to use it. */
            prefix: string;
            /** @description Requests a minute; null means no limit */
            rate_limit_rpm: number | null;
            /** @description Dollars with six decimals, for example "30.000000"; null means no limit */
            monthly_budget_usd: string | null;
            /** @description This calendar month (UTC), dollars with six decimals */
            spend_usd: string;
            semantic_cache: boolean;
            cache_nonzero_temp: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            revoked_at: string | null;
            /** Format: date-time */
            last_used_at: string | null;
            /** @description The dashboard's own playground key, which cannot be changed here */
            builtin: boolean;
        };
        CreatedKey: {
            key: components["schemas"]["ApiKey"];
            /** @description The full key. Shown once; only a hash is stored. */
            secret: string;
        };
        KeyCreate: {
            name: string;
            rate_limit_rpm?: number | null;
            /** @description Dollars, as a string or a number. Null or left out means no limit. */
            monthly_budget_usd?: (string | number) | null;
            semantic_cache?: boolean;
            cache_nonzero_temp?: boolean;
        };
        KeyUpdate: {
            name?: string;
            rate_limit_rpm?: number | null;
            monthly_budget_usd?: (string | number) | null;
            semantic_cache?: boolean;
            cache_nonzero_temp?: boolean;
        };
        Attempt: {
            provider: string;
            model: string;
            /** @enum {string} */
            kind: "primary" | "retry" | "fallback" | "hedge" | "skipped";
            latency_ms: number;
            status?: number;
            error?: string;
            error_kind?: string;
            injected?: boolean;
            estimated?: boolean;
        };
        CacheSplit: {
            /** Format: int64 */
            miss: number;
            /** Format: int64 */
            hit_exact: number;
            /** Format: int64 */
            hit_semantic: number;
            /**
             * Format: int64
             * @description Not cacheable, or the request never reached the cache
             */
            bypass: number;
        };
        UsageTotals: {
            /** Format: int64 */
            requests: number;
            /** Format: int64 */
            input_tokens: number;
            /** Format: int64 */
            output_tokens: number;
            /** @description Dollars with six decimals */
            cost_usd: string;
            /** @description What cache hits avoided spending */
            saved_usd: string;
            /** @description saved / (spent + saved) */
            saved_share: number;
            /** Format: int64 */
            cache_hits: number;
            /**
             * Format: int64
             * @description Requests every provider failed
             */
            errors: number;
            /**
             * Format: int64
             * @description Refused by a rate limit or a budget
             */
            rejected: number;
            cache: components["schemas"]["CacheSplit"];
        };
        UsageGroup: {
            /** @description The day, the model id, or the key id */
            key: string;
            label: string;
            /** Format: int64 */
            requests: number;
            /** Format: int64 */
            input_tokens: number;
            /** Format: int64 */
            output_tokens: number;
            cost_usd: string;
            saved_usd: string;
            /** Format: int64 */
            cache_hits: number;
            /** Format: int64 */
            errors: number;
            /**
             * Format: int64
             * @description Successful requests not served from a cache, which the latency figures use
             */
            timed_requests: number;
            /** @description Model groups only */
            p50_ms: number | null;
            /** @description Model groups only */
            p95_ms: number | null;
            /** @description Day groups only: that day split by model or by key (see `stack`), keyed by model id or key id */
            series?: {
                [key: string]: components["schemas"]["SeriesStat"];
            };
        };
        SeriesStat: {
            /** @description The model id, or the key's name */
            label: string;
            /** Format: int64 */
            requests: number;
            /** Format: int64 */
            input_tokens: number;
            /** Format: int64 */
            output_tokens: number;
            cost_usd: string;
            saved_usd: string;
        };
        ProviderHealth: {
            name: string;
            /** @enum {string} */
            state: "closed" | "open" | "half_open" | "not_configured";
            open_remaining_seconds: number | null;
            reason?: string;
            /** Format: int64 */
            failed_attempts: number;
            /** Format: int64 */
            fallbacks_to: number;
        };
        /** @description Time spent in Spillway itself, not the upstream call. Covers requests since the service started, for all keys. */
        AddedLatency: {
            p50_ms: number;
            p95_ms: number;
            p99_ms: number;
            /** Format: int64 */
            samples: number;
            /** Format: date-time */
            since: string;
        };
        UsageSummary: {
            range: {
                /** Format: date */
                from: string;
                /** Format: date */
                to: string;
                days: number;
            };
            /** @enum {string} */
            group_by: "day" | "model" | "key";
            /** @enum {string} */
            stack: "model" | "key";
            totals: components["schemas"]["UsageTotals"];
            added_latency: components["schemas"]["AddedLatency"] | null;
            providers: components["schemas"]["ProviderHealth"][];
            /** Format: int64 */
            fallbacks_fired: number;
            groups: components["schemas"]["UsageGroup"][];
        };
        RequestLogRow: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            key_id: string | null;
            key_name: string;
            policy: string;
            provider: string;
            model: string;
            input_tokens: number;
            output_tokens: number;
            cost_usd: string;
            saved_usd: string;
            latency_ms: number;
            ttfb_ms: number | null;
            /** @enum {string} */
            cache_status: "miss" | "hit_exact" | "hit_semantic" | "bypass";
            outcome: string;
            attempts: components["schemas"]["Attempt"][];
            /** Format: date-time */
            created_at: string;
        };
        RequestPage: {
            requests: components["schemas"]["RequestLogRow"][];
            next_cursor: string | null;
        };
        Fault: {
            /** @description A provider name from the catalog */
            provider: string;
            /** @enum {string} */
            kind: "rate_limit" | "server_error" | "slow" | "cut_stream";
        };
        CatalogModel: {
            id: string;
            provider: string;
            upstream: string;
            tags: string[];
            context_window: number;
            input_usd_per_mtok: string;
            output_usd_per_mtok: string;
        };
        CatalogPolicy: {
            name: string;
            /** @enum {string} */
            type: "fixed" | "fallback" | "cheapest" | "weighted";
            description: string;
            /** @description In the order they are tried (for weighted, the arms) */
            models: {
                id: string;
                provider: string;
            }[];
            /** @description Distinct providers in the order they would be tried */
            providers: string[];
            weights: number[];
            tag: string;
            hedge_after_ms: number;
        };
        PlaygroundState: {
            key: {
                prefix: string;
                monthly_budget_usd: string | null;
                spend_usd: string;
                rate_limit_rpm: number | null;
            };
            fault_injection: boolean;
            policies: components["schemas"]["CatalogPolicy"][];
        };
        PlaygroundChatRequest: {
            /** @description A policy name or a model id. Default: default */
            policy?: string;
            prompt: string;
            system?: string;
            temperature?: number | null;
            max_tokens?: number | null;
            /** @description Needed for the cut_stream fault */
            stream?: boolean;
            faults?: components["schemas"]["Fault"][];
        };
        PlaygroundResult: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            created_at: string;
            policy: string;
            stream: boolean;
            answer: string;
            finish_reason: string;
            provider: string;
            model: string;
            /** @enum {string} */
            cache: "miss" | "hit_exact" | "hit_semantic" | "bypass";
            input_tokens: number;
            output_tokens: number;
            cost_usd: string;
            saved_usd: string;
            latency_ms: number;
            /** @description Time spent in Spillway rather than at a provider */
            overhead_ms: number;
            outcome: string;
            error: {
                code: string;
                message: string;
            } | null;
            attempts: components["schemas"]["Attempt"][];
            faults: components["schemas"]["Fault"][];
            /** @description Faults that named a provider the policy would not try */
            unused_faults: components["schemas"]["Fault"][];
        };
        PlaygroundHistoryItem: components["schemas"]["PlaygroundResult"] & {
            prompt: string;
            system: string;
        };
        Status: {
            /** @enum {string} */
            postgres: "up" | "down" | "unknown";
            /**
             * @description disabled means REDIS_URL is not set
             * @enum {string}
             */
            redis: "up" | "down" | "disabled";
        };
        Error: {
            error: {
                code: string;
                message: string;
            };
        };
    };
    responses: {
        /** @description The request is not valid */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No token, a bad token, or an expired one */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The signed-in user is a viewer and this needs an admin */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such resource */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description First UTC day, inclusive (YYYY-MM-DD). Default: 13 days before `to`. */
        From: string;
        /** @description Last UTC day, inclusive (YYYY-MM-DD). Default: today. */
        To: string;
        /** @description Only this key */
        KeyId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in */
            200: {
                headers: {
                    /** @description no-store */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description The body was not a username and a password */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The username or password is wrong. The answer is the same for an unknown user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Five failed sign-ins in a minute for this address or username */
            429: {
                headers: {
                    /** @description Seconds until the next try is allowed */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user the token belongs to */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description No token, a bad token, or an expired one (`session_expired`) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dependency status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            /** @description No token, a bad token, or an expired one */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active keys first, then revoked ones */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        keys: components["schemas"]["ApiKey"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeyCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedKey"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    revokeKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The revoked key */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKey"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeyUpdate"];
            };
        };
        responses: {
            /** @description The key after the change */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKey"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The key is revoked and cannot be changed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    usageSummary: {
        parameters: {
            query?: {
                /** @description First UTC day, inclusive (YYYY-MM-DD). Default: 13 days before `to`. */
                from?: components["parameters"]["From"];
                /** @description Last UTC day, inclusive (YYYY-MM-DD). Default: today. */
                to?: components["parameters"]["To"];
                /** @description Only this key */
                key_id?: components["parameters"]["KeyId"];
                group_by?: "day" | "model" | "key";
                /** @description With group_by=day, what each day is split by */
                stack?: "model" | "key";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    usageRequests: {
        parameters: {
            query?: {
                /** @description First UTC day, inclusive (YYYY-MM-DD). Default: 13 days before `to`. */
                from?: components["parameters"]["From"];
                /** @description Last UTC day, inclusive (YYYY-MM-DD). Default: today. */
                to?: components["parameters"]["To"];
                /** @description Only this key */
                key_id?: components["parameters"]["KeyId"];
                model?: string;
                outcome?: string;
                policy?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    usageExport: {
        parameters: {
            query?: {
                /** @description First UTC day, inclusive (YYYY-MM-DD). Default: 13 days before `to`. */
                from?: components["parameters"]["From"];
                /** @description Last UTC day, inclusive (YYYY-MM-DD). Default: today. */
                to?: components["parameters"]["To"];
                /** @description Only this key */
                key_id?: components["parameters"]["KeyId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A CSV file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Models and policies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        models: components["schemas"]["CatalogModel"][];
                        policies: components["schemas"]["CatalogPolicy"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    playgroundState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description State */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaygroundState"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    playgroundChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaygroundChatRequest"];
            };
        };
        responses: {
            /** @description The route taken and the answer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaygroundResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description The playground key's monthly budget is used up */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            403: components["responses"]["Forbidden"];
            /** @description The playground key's rate limit was hit */
            429: {
                headers: {
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    playgroundHistory: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        requests: components["schemas"]["PlaygroundHistoryItem"][];
                        next_cursor: string | null;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
}
