/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with a username and password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user and their role */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether Spillway's dependencies are reachable */
        get: operations["status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every key with its limits and this month's spend. Never the key itself. */
        get: operations["listKeys"];
        put?: never;
        /** Create a key. The full key is in the response once and can never be shown again. */
        post: operations["createKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a key. The gateway rejects it from the next request. Revoking twice changes nothing. */
        delete: operations["revokeKey"];
        options?: never;
        head?: never;
        /** Change a key's name, limits or cache settings. A field left out is unchanged; null removes a limit. */
        patch: operations["updateKey"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Role: "admin" | "viewer";
        LoginRequest: {
            username: string;
            password: string;
        };
        User: {
            username: string;
            role: components["schemas"]["Role"];
        };
        LoginResponse: {
            token: string;
            /** Format: date-time */
            expires_at: string;
            user: components["schemas"]["User"];
        };
        ApiKey: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description The first characters of the key, for recognising it. Never enough to use it. */
            prefix: string;
            /** @description Requests a minute; null means no limit */
            rate_limit_rpm: number | null;
            /** @description Dollars with six decimals, for example "30.000000"; null means no limit */
            monthly_budget_usd: string | null;
            /** @description This calendar month (UTC), dollars with six decimals */
            spend_usd: string;
            semantic_cache: boolean;
            cache_nonzero_temp: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            revoked_at: string | null;
            /** Format: date-time */
            last_used_at: string | null;
            /** @description The dashboard's own playground key, which cannot be changed here */
            builtin: boolean;
        };
        CreatedKey: {
            key: components["schemas"]["ApiKey"];
            /** @description The full key. Shown once; only a hash is stored. */
            secret: string;
        };
        KeyCreate: {
            name: string;
            rate_limit_rpm?: number | null;
            /** @description Dollars, as a string or a number. Null or left out means no limit. */
            monthly_budget_usd?: (string | number) | null;
            semantic_cache?: boolean;
            cache_nonzero_temp?: boolean;
        };
        KeyUpdate: {
            name?: string;
            rate_limit_rpm?: number | null;
            monthly_budget_usd?: (string | number) | null;
            semantic_cache?: boolean;
            cache_nonzero_temp?: boolean;
        };
        Status: {
            /** @enum {string} */
            postgres: "up" | "down" | "unknown";
            /**
             * @description disabled means REDIS_URL is not set
             * @enum {string}
             */
            redis: "up" | "down" | "disabled";
        };
        Error: {
            error: {
                code: string;
                message: string;
            };
        };
    };
    responses: {
        /** @description The request is not valid */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No token, a bad token, or an expired one */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The signed-in user is a viewer and this needs an admin */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such resource */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in */
            200: {
                headers: {
                    /** @description no-store */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description The body was not a username and a password */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The username or password is wrong. The answer is the same for an unknown user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Five failed sign-ins in a minute for this address or username */
            429: {
                headers: {
                    /** @description Seconds until the next try is allowed */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user the token belongs to */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description No token, a bad token, or an expired one (`session_expired`) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dependency status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            /** @description No token, a bad token, or an expired one */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active keys first, then revoked ones */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        keys: components["schemas"]["ApiKey"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeyCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedKey"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    revokeKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The revoked key */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKey"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeyUpdate"];
            };
        };
        responses: {
            /** @description The key after the change */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKey"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The key is revoked and cannot be changed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
