import fs from "node:fs";
import path from "node:path";

type Value = { value: string };
type Theme = {
  colorScheme: string;
  color: Record<string, Value>;
  type: Record<string, string>;
  badge: Record<string, string>;
  button: Record<string, string>;
  tab: { radius: string };
};
export type Tokens = {
  themes: { dark: Theme; light: Theme };
  shared: {
    font: { sans: string; mono: string };
    radius: Record<string, string>;
    layout: Record<string, string>;
  };
};

export const root = path.resolve(__dirname, "..");
export const tokensJson = path.resolve(root, "../docs/design/tokens.json");
export const designCss = path.resolve(root, "../docs/design/tokens.css");
export const outCss = path.resolve(root, "src/styles/tokens.css");

function themeBlock(t: Theme): string[] {
  const lines = [`  color-scheme: ${t.colorScheme};`, ""];
  for (const [k, v] of Object.entries(t.color)) lines.push(`  --${k}: ${v.value};`);
  lines.push("");
  for (const [k, v] of Object.entries(t.type)) lines.push(`  --${k}: ${v};`);
  lines.push("");
  for (const [k, v] of Object.entries(t.badge)) lines.push(`  --badge-${k}: ${v};`);
  lines.push("");
  lines.push(`  --btn-h: ${t.button.h};`, `  --btn-py: ${t.button.py};`, `  --btn-px: ${t.button.px};`);
  lines.push(`  --r-tab: ${t.tab.radius};`);
  return lines;
}

/** Builds src/styles/tokens.css from docs/design/tokens.json. The two themes stay separate token sets. */
export function generate(tokens: Tokens): string {
  const s = tokens.shared;
  const out = [
    "/* Generated by `npm run tokens` from docs/design/tokens.json. Do not edit by hand. */",
    "",
    ':root,\n:root[data-theme="dark"] {',
    ...themeBlock(tokens.themes.dark),
    "}",
    "",
    ':root[data-theme="light"] {',
    ...themeBlock(tokens.themes.light),
    "}",
    "",
    "/* Shared by both themes. */",
    ":root {",
    `  --ff-sans: ${s.font.sans};`,
    `  --ff-mono: ${s.font.mono};`,
    `  --r-button: ${s.radius.button};`,
    `  --r-card: ${s.radius.card};`,
    `  --r-pill: ${s.radius.pill};`,
    `  --sidebar-w: ${s.layout.sidebar};`,
    "}",
    "",
  ];
  return out.join("\n");
}

export function readTokens(): Tokens {
  return JSON.parse(fs.readFileSync(tokensJson, "utf8")) as Tokens;
}

const norm = (v: string) => v.replace(/\s*,\s*/g, ",").replace(/"/g, "'").trim();

/** Parses `--name: value;` declarations per theme block out of a CSS file. */
export function parseVars(css: string): { dark: Record<string, string>; light: Record<string, string>; shared: Record<string, string> } {
  const blocks = { dark: {}, light: {}, shared: {} } as Record<string, Record<string, string>>;
  const re = /([^{}]+)\{([^}]*)\}/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(css.replace(/\/\*[\s\S]*?\*\//g, "")))) {
    const sel = m[1].trim();
    const which = sel.includes('data-theme="light"') ? "light" : sel.includes('data-theme="dark"') ? "dark" : sel === ":root" ? "shared" : null;
    if (!which) continue;
    for (const d of m[2].matchAll(/--([\w-]+)\s*:\s*([^;]+);/g)) blocks[which][d[1]] = norm(d[2]);
  }
  return blocks as { dark: Record<string, string>; light: Record<string, string>; shared: Record<string, string> };
}

/** Every variable in the hand-exported docs/design/tokens.css must have the same value in the generated file. */
export function driftAgainstDesignCss(generated: string, designCssText: string): string[] {
  const g = parseVars(generated);
  const d = parseVars(designCssText);
  const problems: string[] = [];
  for (const theme of ["dark", "light", "shared"] as const) {
    for (const [k, v] of Object.entries(d[theme])) {
      if (!(k in g[theme])) problems.push(`${theme}: --${k} is in docs/design/tokens.css but not generated`);
      else if (g[theme][k] !== v) problems.push(`${theme}: --${k} is ${g[theme][k]} in tokens.json but ${v} in docs/design/tokens.css`);
    }
  }
  return problems;
}
