// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: keys.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one

INSERT INTO api_keys (id, name, key_prefix, key_hash, rate_limit_rpm, monthly_budget_usd, semantic_cache, cache_nonzero_temp)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING created_at
`

type CreateAPIKeyParams struct {
	ID               uuid.UUID
	Name             string
	KeyPrefix        string
	KeyHash          []byte
	RateLimitRpm     pgtype.Int4
	MonthlyBudgetUsd pgtype.Numeric
	SemanticCache    bool
	CacheNonzeroTemp bool
}

// Money is numeric(14,8) in the database. internal/db converts to and from micro-dollars (int64).
func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.RateLimitRpm,
		arg.MonthlyBudgetUsd,
		arg.SemanticCache,
		arg.CacheNonzeroTemp,
	)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, name, key_prefix, rate_limit_rpm, monthly_budget_usd, semantic_cache, cache_nonzero_temp, created_at, revoked_at
FROM api_keys WHERE id = $1
`

type GetAPIKeyByIDRow struct {
	ID               uuid.UUID
	Name             string
	KeyPrefix        string
	RateLimitRpm     pgtype.Int4
	MonthlyBudgetUsd pgtype.Numeric
	SemanticCache    bool
	CacheNonzeroTemp bool
	CreatedAt        time.Time
	RevokedAt        *time.Time
}

func (q *Queries) GetAPIKeyByID(ctx context.Context, id uuid.UUID) (GetAPIKeyByIDRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, id)
	var i GetAPIKeyByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyPrefix,
		&i.RateLimitRpm,
		&i.MonthlyBudgetUsd,
		&i.SemanticCache,
		&i.CacheNonzeroTemp,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveAPIKeyByHash = `-- name: GetActiveAPIKeyByHash :one
SELECT id, name, key_prefix, rate_limit_rpm, monthly_budget_usd, semantic_cache, cache_nonzero_temp, created_at, revoked_at
FROM api_keys
WHERE key_hash = $1 AND revoked_at IS NULL
`

type GetActiveAPIKeyByHashRow struct {
	ID               uuid.UUID
	Name             string
	KeyPrefix        string
	RateLimitRpm     pgtype.Int4
	MonthlyBudgetUsd pgtype.Numeric
	SemanticCache    bool
	CacheNonzeroTemp bool
	CreatedAt        time.Time
	RevokedAt        *time.Time
}

func (q *Queries) GetActiveAPIKeyByHash(ctx context.Context, keyHash []byte) (GetActiveAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getActiveAPIKeyByHash, keyHash)
	var i GetActiveAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyPrefix,
		&i.RateLimitRpm,
		&i.MonthlyBudgetUsd,
		&i.SemanticCache,
		&i.CacheNonzeroTemp,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, name, key_prefix, rate_limit_rpm, monthly_budget_usd, semantic_cache, cache_nonzero_temp, created_at, revoked_at
FROM api_keys
ORDER BY created_at DESC, id DESC
`

type ListAPIKeysRow struct {
	ID               uuid.UUID
	Name             string
	KeyPrefix        string
	RateLimitRpm     pgtype.Int4
	MonthlyBudgetUsd pgtype.Numeric
	SemanticCache    bool
	CacheNonzeroTemp bool
	CreatedAt        time.Time
	RevokedAt        *time.Time
}

func (q *Queries) ListAPIKeys(ctx context.Context) ([]ListAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIKeysRow
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeyPrefix,
			&i.RateLimitRpm,
			&i.MonthlyBudgetUsd,
			&i.SemanticCache,
			&i.CacheNonzeroTemp,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIKeysWithStats = `-- name: ListAPIKeysWithStats :many
SELECT k.id, k.name, k.key_prefix, k.rate_limit_rpm, k.monthly_budget_usd, k.semantic_cache, k.cache_nonzero_temp,
       k.created_at, k.revoked_at,
       COALESCE((SELECT SUM(d.cost_usd) FROM usage_daily d WHERE d.api_key_id = k.id AND d.day >= $1), 0)::numeric AS spend_usd,
       COALESCE((SELECT MAX(u.created_at) FROM usage u WHERE u.api_key_id = k.id), 'epoch'::timestamptz)::timestamptz AS last_used_at -- epoch means never used
FROM api_keys k
ORDER BY (k.revoked_at IS NOT NULL), k.created_at DESC, k.id DESC
`

type ListAPIKeysWithStatsRow struct {
	ID               uuid.UUID
	Name             string
	KeyPrefix        string
	RateLimitRpm     pgtype.Int4
	MonthlyBudgetUsd pgtype.Numeric
	SemanticCache    bool
	CacheNonzeroTemp bool
	CreatedAt        time.Time
	RevokedAt        *time.Time
	SpendUsd         pgtype.Numeric
	LastUsedAt       time.Time
}

func (q *Queries) ListAPIKeysWithStats(ctx context.Context, since pgtype.Date) ([]ListAPIKeysWithStatsRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeysWithStats, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIKeysWithStatsRow
	for rows.Next() {
		var i ListAPIKeysWithStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeyPrefix,
			&i.RateLimitRpm,
			&i.MonthlyBudgetUsd,
			&i.SemanticCache,
			&i.CacheNonzeroTemp,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.SpendUsd,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL RETURNING id
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const setSemanticCache = `-- name: SetSemanticCache :one
UPDATE api_keys SET semantic_cache = $1 WHERE key_hash = $2 RETURNING id
`

type SetSemanticCacheParams struct {
	SemanticCache bool
	KeyHash       []byte
}

func (q *Queries) SetSemanticCache(ctx context.Context, arg SetSemanticCacheParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, setSemanticCache, arg.SemanticCache, arg.KeyHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateAPIKey = `-- name: UpdateAPIKey :one
UPDATE api_keys SET
  name               = COALESCE($1, name),
  rate_limit_rpm     = CASE WHEN $2::bool THEN $3 ELSE rate_limit_rpm END,
  monthly_budget_usd = CASE WHEN $4::bool THEN $5 ELSE monthly_budget_usd END,
  semantic_cache     = COALESCE($6, semantic_cache),
  cache_nonzero_temp = COALESCE($7, cache_nonzero_temp)
WHERE id = $8 AND revoked_at IS NULL
RETURNING id
`

type UpdateAPIKeyParams struct {
	Name             pgtype.Text
	SetRpm           bool
	RateLimitRpm     pgtype.Int4
	SetBudget        bool
	MonthlyBudgetUsd pgtype.Numeric
	SemanticCache    pgtype.Bool
	CacheNonzeroTemp pgtype.Bool
	ID               uuid.UUID
}

func (q *Queries) UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateAPIKey,
		arg.Name,
		arg.SetRpm,
		arg.RateLimitRpm,
		arg.SetBudget,
		arg.MonthlyBudgetUsd,
		arg.SemanticCache,
		arg.CacheNonzeroTemp,
		arg.ID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
