// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID               uuid.UUID
	Name             string
	KeyPrefix        string
	KeyHash          []byte
	RateLimitRpm     pgtype.Int4
	MonthlyBudgetUsd pgtype.Numeric
	SemanticCache    bool
	CacheNonzeroTemp bool
	CreatedAt        time.Time
	RevokedAt        *time.Time
}

type SemanticCache struct {
	ID         uuid.UUID
	Scope      uuid.UUID
	ModelGroup string
	Embedding  string
	Response   []byte
	CostUsd    pgtype.Numeric
	CreatedAt  time.Time
	ExpiresAt  time.Time
}

type Usage struct {
	ID           uuid.UUID
	ApiKeyID     uuid.NullUUID
	RunID        uuid.NullUUID
	Policy       string
	Provider     pgtype.Text
	Model        pgtype.Text
	InputTokens  int32
	OutputTokens int32
	CostUsd      pgtype.Numeric
	SavedUsd     pgtype.Numeric
	LatencyMs    int32
	TtfbMs       pgtype.Int4
	CacheStatus  string
	Outcome      string
	Attempts     []byte
	CreatedAt    time.Time
}

type UsageDaily struct {
	ApiKeyID     uuid.UUID
	Day          pgtype.Date
	Model        string
	Requests     int64
	InputTokens  int64
	OutputTokens int64
	CostUsd      pgtype.Numeric
	SavedUsd     pgtype.Numeric
	CacheHits    int64
}

type User struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	Role         string
	CreatedAt    time.Time
}
