// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: playground.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAPIKeyByName = `-- name: GetAPIKeyByName :one
SELECT id, name, key_prefix, rate_limit_rpm, monthly_budget_usd, semantic_cache, cache_nonzero_temp, created_at, revoked_at
FROM api_keys WHERE name = $1 ORDER BY created_at LIMIT 1
`

type GetAPIKeyByNameRow struct {
	ID               uuid.UUID
	Name             string
	KeyPrefix        string
	RateLimitRpm     pgtype.Int4
	MonthlyBudgetUsd pgtype.Numeric
	SemanticCache    bool
	CacheNonzeroTemp bool
	CreatedAt        time.Time
	RevokedAt        *time.Time
}

func (q *Queries) GetAPIKeyByName(ctx context.Context, name string) (GetAPIKeyByNameRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByName, name)
	var i GetAPIKeyByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyPrefix,
		&i.RateLimitRpm,
		&i.MonthlyBudgetUsd,
		&i.SemanticCache,
		&i.CacheNonzeroTemp,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getPlaygroundHistory = `-- name: GetPlaygroundHistory :one
SELECT id, policy, prompt, system, answer, stream, faults, result, created_at FROM playground_history WHERE id = $1
`

func (q *Queries) GetPlaygroundHistory(ctx context.Context, id uuid.UUID) (PlaygroundHistory, error) {
	row := q.db.QueryRow(ctx, getPlaygroundHistory, id)
	var i PlaygroundHistory
	err := row.Scan(
		&i.ID,
		&i.Policy,
		&i.Prompt,
		&i.System,
		&i.Answer,
		&i.Stream,
		&i.Faults,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const insertPlaygroundHistory = `-- name: InsertPlaygroundHistory :exec
INSERT INTO playground_history (id, policy, prompt, system, answer, stream, faults, result, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertPlaygroundHistoryParams struct {
	ID        uuid.UUID
	Policy    string
	Prompt    string
	System    string
	Answer    string
	Stream    bool
	Faults    []byte
	Result    []byte
	CreatedAt time.Time
}

func (q *Queries) InsertPlaygroundHistory(ctx context.Context, arg InsertPlaygroundHistoryParams) error {
	_, err := q.db.Exec(ctx, insertPlaygroundHistory,
		arg.ID,
		arg.Policy,
		arg.Prompt,
		arg.System,
		arg.Answer,
		arg.Stream,
		arg.Faults,
		arg.Result,
		arg.CreatedAt,
	)
	return err
}

const listPlaygroundHistory = `-- name: ListPlaygroundHistory :many
SELECT id, policy, prompt, system, answer, stream, faults, result, created_at
FROM playground_history
WHERE ($1::timestamptz IS NULL OR (created_at, id) < ($1::timestamptz, $2::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListPlaygroundHistoryParams struct {
	BeforeTs *time.Time
	BeforeID uuid.NullUUID
	RowLimit int32
}

func (q *Queries) ListPlaygroundHistory(ctx context.Context, arg ListPlaygroundHistoryParams) ([]PlaygroundHistory, error) {
	rows, err := q.db.Query(ctx, listPlaygroundHistory, arg.BeforeTs, arg.BeforeID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlaygroundHistory
	for rows.Next() {
		var i PlaygroundHistory
		if err := rows.Scan(
			&i.ID,
			&i.Policy,
			&i.Prompt,
			&i.System,
			&i.Answer,
			&i.Stream,
			&i.Faults,
			&i.Result,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAPIKeyLimits = `-- name: SetAPIKeyLimits :exec
UPDATE api_keys SET rate_limit_rpm = $1, monthly_budget_usd = $2 WHERE id = $3
`

type SetAPIKeyLimitsParams struct {
	RateLimitRpm     pgtype.Int4
	MonthlyBudgetUsd pgtype.Numeric
	ID               uuid.UUID
}

func (q *Queries) SetAPIKeyLimits(ctx context.Context, arg SetAPIKeyLimitsParams) error {
	_, err := q.db.Exec(ctx, setAPIKeyLimits, arg.RateLimitRpm, arg.MonthlyBudgetUsd, arg.ID)
	return err
}
