// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const reportByDayModel = `-- name: ReportByDayModel :many
SELECT
  (created_at AT TIME ZONE 'UTC')::date                AS day,
  COALESCE(model, '')::text                            AS model,
  count(*)::bigint                                     AS requests,
  COALESCE(sum(input_tokens), 0)::bigint               AS input_tokens,
  COALESCE(sum(output_tokens), 0)::bigint              AS output_tokens,
  COALESCE(sum(cost_usd), 0)::numeric                  AS cost_usd,
  COALESCE(sum(saved_usd), 0)::numeric                 AS saved_usd,
  count(*) FILTER (WHERE cache_status IN ('hit_exact', 'hit_semantic'))::bigint AS cache_hits,
  count(*) FILTER (WHERE outcome IN ('upstream_error', 'all_providers_failed'))::bigint AS errors
FROM usage
WHERE created_at >= $1 AND created_at < $2
  AND ($3::uuid IS NULL OR api_key_id = $3::uuid)
GROUP BY 1, 2
ORDER BY 1, 2
`

type ReportByDayModelParams struct {
	FromTs time.Time
	ToTs   time.Time
	KeyID  uuid.NullUUID
}

type ReportByDayModelRow struct {
	Day          pgtype.Date
	Model        string
	Requests     int64
	InputTokens  int64
	OutputTokens int64
	CostUsd      pgtype.Numeric
	SavedUsd     pgtype.Numeric
	CacheHits    int64
	Errors       int64
}

func (q *Queries) ReportByDayModel(ctx context.Context, arg ReportByDayModelParams) ([]ReportByDayModelRow, error) {
	rows, err := q.db.Query(ctx, reportByDayModel, arg.FromTs, arg.ToTs, arg.KeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportByDayModelRow
	for rows.Next() {
		var i ReportByDayModelRow
		if err := rows.Scan(
			&i.Day,
			&i.Model,
			&i.Requests,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostUsd,
			&i.SavedUsd,
			&i.CacheHits,
			&i.Errors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportByKey = `-- name: ReportByKey :many
SELECT
  u.api_key_id                                         AS key_id,
  COALESCE(k.name, '(deleted key)')::text              AS key_name,
  count(*)::bigint                                     AS requests,
  COALESCE(sum(u.input_tokens), 0)::bigint             AS input_tokens,
  COALESCE(sum(u.output_tokens), 0)::bigint            AS output_tokens,
  COALESCE(sum(u.cost_usd), 0)::numeric                AS cost_usd,
  COALESCE(sum(u.saved_usd), 0)::numeric               AS saved_usd,
  count(*) FILTER (WHERE u.cache_status IN ('hit_exact', 'hit_semantic'))::bigint AS cache_hits,
  count(*) FILTER (WHERE u.outcome IN ('upstream_error', 'all_providers_failed'))::bigint AS errors
FROM usage u LEFT JOIN api_keys k ON k.id = u.api_key_id
WHERE u.created_at >= $1 AND u.created_at < $2
  AND ($3::uuid IS NULL OR u.api_key_id = $3::uuid)
GROUP BY u.api_key_id, k.name
ORDER BY sum(u.cost_usd) DESC NULLS LAST, count(*) DESC
`

type ReportByKeyParams struct {
	FromTs time.Time
	ToTs   time.Time
	KeyID  uuid.NullUUID
}

type ReportByKeyRow struct {
	KeyID        uuid.NullUUID
	KeyName      string
	Requests     int64
	InputTokens  int64
	OutputTokens int64
	CostUsd      pgtype.Numeric
	SavedUsd     pgtype.Numeric
	CacheHits    int64
	Errors       int64
}

func (q *Queries) ReportByKey(ctx context.Context, arg ReportByKeyParams) ([]ReportByKeyRow, error) {
	rows, err := q.db.Query(ctx, reportByKey, arg.FromTs, arg.ToTs, arg.KeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportByKeyRow
	for rows.Next() {
		var i ReportByKeyRow
		if err := rows.Scan(
			&i.KeyID,
			&i.KeyName,
			&i.Requests,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostUsd,
			&i.SavedUsd,
			&i.CacheHits,
			&i.Errors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportByModel = `-- name: ReportByModel :many
SELECT
  COALESCE(model, '')::text                            AS model,
  count(*)::bigint                                     AS requests,
  COALESCE(sum(input_tokens), 0)::bigint               AS input_tokens,
  COALESCE(sum(output_tokens), 0)::bigint              AS output_tokens,
  COALESCE(sum(cost_usd), 0)::numeric                  AS cost_usd,
  COALESCE(sum(saved_usd), 0)::numeric                 AS saved_usd,
  count(*) FILTER (WHERE cache_status IN ('hit_exact', 'hit_semantic'))::bigint AS cache_hits,
  count(*) FILTER (WHERE outcome IN ('upstream_error', 'all_providers_failed'))::bigint AS errors,
  -- Latency is judged on requests that really went to a provider and succeeded: a cache hit says nothing about the model.
  count(*) FILTER (WHERE outcome = 'ok' AND cache_status IN ('miss', 'bypass'))::bigint AS timed_requests,
  COALESCE(percentile_cont(0.5)  WITHIN GROUP (ORDER BY latency_ms) FILTER (WHERE outcome = 'ok' AND cache_status IN ('miss', 'bypass')), 0)::float8 AS p50_ms,
  COALESCE(percentile_cont(0.95) WITHIN GROUP (ORDER BY latency_ms) FILTER (WHERE outcome = 'ok' AND cache_status IN ('miss', 'bypass')), 0)::float8 AS p95_ms
FROM usage
WHERE created_at >= $1 AND created_at < $2
  AND ($3::uuid IS NULL OR api_key_id = $3::uuid)
GROUP BY 1
ORDER BY sum(cost_usd) DESC NULLS LAST, count(*) DESC, 1
`

type ReportByModelParams struct {
	FromTs time.Time
	ToTs   time.Time
	KeyID  uuid.NullUUID
}

type ReportByModelRow struct {
	Model         string
	Requests      int64
	InputTokens   int64
	OutputTokens  int64
	CostUsd       pgtype.Numeric
	SavedUsd      pgtype.Numeric
	CacheHits     int64
	Errors        int64
	TimedRequests int64
	P50Ms         float64
	P95Ms         float64
}

func (q *Queries) ReportByModel(ctx context.Context, arg ReportByModelParams) ([]ReportByModelRow, error) {
	rows, err := q.db.Query(ctx, reportByModel, arg.FromTs, arg.ToTs, arg.KeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportByModelRow
	for rows.Next() {
		var i ReportByModelRow
		if err := rows.Scan(
			&i.Model,
			&i.Requests,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostUsd,
			&i.SavedUsd,
			&i.CacheHits,
			&i.Errors,
			&i.TimedRequests,
			&i.P50Ms,
			&i.P95Ms,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportCSVRows = `-- name: ReportCSVRows :many
SELECT
  (u.created_at AT TIME ZONE 'UTC')::date              AS day,
  COALESCE(k.name, '(deleted key)')::text              AS key_name,
  COALESCE(u.model, '')::text                          AS model,
  count(*)::bigint                                     AS requests,
  COALESCE(sum(u.input_tokens), 0)::bigint             AS input_tokens,
  COALESCE(sum(u.output_tokens), 0)::bigint            AS output_tokens,
  COALESCE(sum(u.cost_usd), 0)::numeric                AS cost_usd,
  COALESCE(sum(u.saved_usd), 0)::numeric               AS saved_usd,
  count(*) FILTER (WHERE u.cache_status IN ('hit_exact', 'hit_semantic'))::bigint AS cache_hits,
  count(*) FILTER (WHERE u.outcome IN ('upstream_error', 'all_providers_failed'))::bigint AS errors
FROM usage u LEFT JOIN api_keys k ON k.id = u.api_key_id
WHERE u.created_at >= $1 AND u.created_at < $2
  AND ($3::uuid IS NULL OR u.api_key_id = $3::uuid)
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3
`

type ReportCSVRowsParams struct {
	FromTs time.Time
	ToTs   time.Time
	KeyID  uuid.NullUUID
}

type ReportCSVRowsRow struct {
	Day          pgtype.Date
	KeyName      string
	Model        string
	Requests     int64
	InputTokens  int64
	OutputTokens int64
	CostUsd      pgtype.Numeric
	SavedUsd     pgtype.Numeric
	CacheHits    int64
	Errors       int64
}

func (q *Queries) ReportCSVRows(ctx context.Context, arg ReportCSVRowsParams) ([]ReportCSVRowsRow, error) {
	rows, err := q.db.Query(ctx, reportCSVRows, arg.FromTs, arg.ToTs, arg.KeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportCSVRowsRow
	for rows.Next() {
		var i ReportCSVRowsRow
		if err := rows.Scan(
			&i.Day,
			&i.KeyName,
			&i.Model,
			&i.Requests,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostUsd,
			&i.SavedUsd,
			&i.CacheHits,
			&i.Errors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportProviderAttempts = `-- name: ReportProviderAttempts :many
SELECT
  COALESCE(a->>'provider', '')::text                   AS provider,
  count(*) FILTER (WHERE COALESCE(a->>'error_kind', '') <> '' AND a->>'kind' <> 'skipped')::bigint AS failed_attempts,
  count(*) FILTER (WHERE a->>'kind' = 'fallback')::bigint                                          AS fallbacks_to
FROM usage u, jsonb_array_elements(u.attempts) a
WHERE u.created_at >= $1 AND u.created_at < $2
  AND ($3::uuid IS NULL OR u.api_key_id = $3::uuid)
GROUP BY 1
ORDER BY 1
`

type ReportProviderAttemptsParams struct {
	FromTs time.Time
	ToTs   time.Time
	KeyID  uuid.NullUUID
}

type ReportProviderAttemptsRow struct {
	Provider       string
	FailedAttempts int64
	FallbacksTo    int64
}

// Failed attempts and fallbacks per provider, read out of the attempts recorded on each request.
func (q *Queries) ReportProviderAttempts(ctx context.Context, arg ReportProviderAttemptsParams) ([]ReportProviderAttemptsRow, error) {
	rows, err := q.db.Query(ctx, reportProviderAttempts, arg.FromTs, arg.ToTs, arg.KeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportProviderAttemptsRow
	for rows.Next() {
		var i ReportProviderAttemptsRow
		if err := rows.Scan(&i.Provider, &i.FailedAttempts, &i.FallbacksTo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportRequests = `-- name: ReportRequests :many
SELECT u.id, u.api_key_id, COALESCE(k.name, '')::text AS key_name, u.run_id, u.policy, u.provider, u.model,
       u.input_tokens, u.output_tokens, u.cost_usd, u.saved_usd, u.latency_ms, u.ttfb_ms, u.cache_status, u.outcome,
       u.attempts, u.created_at
FROM usage u LEFT JOIN api_keys k ON k.id = u.api_key_id
WHERE u.created_at >= $1 AND u.created_at < $2
  AND ($3::uuid IS NULL OR u.api_key_id = $3::uuid)
  AND ($4::text IS NULL OR u.model = $4::text)
  AND ($5::text IS NULL OR u.outcome = $5::text)
  AND ($6::text IS NULL OR u.policy = $6::text)
  AND ($7::timestamptz IS NULL OR (u.created_at, u.id) < ($7::timestamptz, $8::uuid))
ORDER BY u.created_at DESC, u.id DESC
LIMIT $9
`

type ReportRequestsParams struct {
	FromTs   time.Time
	ToTs     time.Time
	KeyID    uuid.NullUUID
	Model    pgtype.Text
	Outcome  pgtype.Text
	Policy   pgtype.Text
	BeforeTs *time.Time
	BeforeID uuid.NullUUID
	RowLimit int32
}

type ReportRequestsRow struct {
	ID           uuid.UUID
	ApiKeyID     uuid.NullUUID
	KeyName      string
	RunID        uuid.NullUUID
	Policy       string
	Provider     pgtype.Text
	Model        pgtype.Text
	InputTokens  int32
	OutputTokens int32
	CostUsd      pgtype.Numeric
	SavedUsd     pgtype.Numeric
	LatencyMs    int32
	TtfbMs       pgtype.Int4
	CacheStatus  string
	Outcome      string
	Attempts     []byte
	CreatedAt    time.Time
}

// Newest first, keyset-paged on (created_at, id).
func (q *Queries) ReportRequests(ctx context.Context, arg ReportRequestsParams) ([]ReportRequestsRow, error) {
	rows, err := q.db.Query(ctx, reportRequests,
		arg.FromTs,
		arg.ToTs,
		arg.KeyID,
		arg.Model,
		arg.Outcome,
		arg.Policy,
		arg.BeforeTs,
		arg.BeforeID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportRequestsRow
	for rows.Next() {
		var i ReportRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.ApiKeyID,
			&i.KeyName,
			&i.RunID,
			&i.Policy,
			&i.Provider,
			&i.Model,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostUsd,
			&i.SavedUsd,
			&i.LatencyMs,
			&i.TtfbMs,
			&i.CacheStatus,
			&i.Outcome,
			&i.Attempts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportTotals = `-- name: ReportTotals :one

SELECT
  count(*)::bigint                                                          AS requests,
  COALESCE(sum(input_tokens), 0)::bigint                                    AS input_tokens,
  COALESCE(sum(output_tokens), 0)::bigint                                   AS output_tokens,
  COALESCE(sum(cost_usd), 0)::numeric                                       AS cost_usd,
  COALESCE(sum(saved_usd), 0)::numeric                                      AS saved_usd,
  count(*) FILTER (WHERE outcome IN ('upstream_error', 'all_providers_failed'))::bigint AS errors,
  count(*) FILTER (WHERE outcome IN ('rate_limited', 'over_budget'))::bigint            AS rejected,
  count(*) FILTER (WHERE cache_status = 'miss')::bigint                     AS cache_miss,
  count(*) FILTER (WHERE cache_status = 'hit_exact')::bigint                AS cache_hit_exact,
  count(*) FILTER (WHERE cache_status = 'hit_semantic')::bigint             AS cache_hit_semantic,
  count(*) FILTER (WHERE cache_status = 'bypass')::bigint                   AS cache_bypass
FROM usage
WHERE created_at >= $1 AND created_at < $2
  AND ($3::uuid IS NULL OR api_key_id = $3::uuid)
`

type ReportTotalsParams struct {
	FromTs time.Time
	ToTs   time.Time
	KeyID  uuid.NullUUID
}

type ReportTotalsRow struct {
	Requests         int64
	InputTokens      int64
	OutputTokens     int64
	CostUsd          pgtype.Numeric
	SavedUsd         pgtype.Numeric
	Errors           int64
	Rejected         int64
	CacheMiss        int64
	CacheHitExact    int64
	CacheHitSemantic int64
	CacheBypass      int64
}

// Reports read the per-request `usage` table so that every figure can be checked with a plain SUM over it.
// The range is [from_ts, to_ts), in UTC; an optional key narrows it.
func (q *Queries) ReportTotals(ctx context.Context, arg ReportTotalsParams) (ReportTotalsRow, error) {
	row := q.db.QueryRow(ctx, reportTotals, arg.FromTs, arg.ToTs, arg.KeyID)
	var i ReportTotalsRow
	err := row.Scan(
		&i.Requests,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CostUsd,
		&i.SavedUsd,
		&i.Errors,
		&i.Rejected,
		&i.CacheMiss,
		&i.CacheHitExact,
		&i.CacheHitSemantic,
		&i.CacheBypass,
	)
	return i, err
}
