// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUsage = `-- name: GetUsage :one
SELECT id, api_key_id, run_id, policy, provider, model, input_tokens, output_tokens, cost_usd, saved_usd,
       latency_ms, ttfb_ms, cache_status, outcome, attempts, created_at
FROM usage WHERE id = $1
`

func (q *Queries) GetUsage(ctx context.Context, id uuid.UUID) (Usage, error) {
	row := q.db.QueryRow(ctx, getUsage, id)
	var i Usage
	err := row.Scan(
		&i.ID,
		&i.ApiKeyID,
		&i.RunID,
		&i.Policy,
		&i.Provider,
		&i.Model,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CostUsd,
		&i.SavedUsd,
		&i.LatencyMs,
		&i.TtfbMs,
		&i.CacheStatus,
		&i.Outcome,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const getUsageDaily = `-- name: GetUsageDaily :one
SELECT requests, input_tokens, output_tokens, cost_usd, saved_usd, cache_hits
FROM usage_daily WHERE api_key_id = $1 AND day = $2 AND model = $3
`

type GetUsageDailyParams struct {
	ApiKeyID uuid.UUID
	Day      pgtype.Date
	Model    string
}

type GetUsageDailyRow struct {
	Requests     int64
	InputTokens  int64
	OutputTokens int64
	CostUsd      pgtype.Numeric
	SavedUsd     pgtype.Numeric
	CacheHits    int64
}

func (q *Queries) GetUsageDaily(ctx context.Context, arg GetUsageDailyParams) (GetUsageDailyRow, error) {
	row := q.db.QueryRow(ctx, getUsageDaily, arg.ApiKeyID, arg.Day, arg.Model)
	var i GetUsageDailyRow
	err := row.Scan(
		&i.Requests,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CostUsd,
		&i.SavedUsd,
		&i.CacheHits,
	)
	return i, err
}

const insertUsage = `-- name: InsertUsage :exec
INSERT INTO usage (
  id, api_key_id, run_id, policy, provider, model, input_tokens, output_tokens,
  cost_usd, saved_usd, latency_ms, ttfb_ms, cache_status, outcome, attempts, created_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8,
  $9, $10, $11, $12, $13, $14, $15, $16
)
`

type InsertUsageParams struct {
	ID           uuid.UUID
	ApiKeyID     uuid.NullUUID
	RunID        uuid.NullUUID
	Policy       string
	Provider     pgtype.Text
	Model        pgtype.Text
	InputTokens  int32
	OutputTokens int32
	CostUsd      pgtype.Numeric
	SavedUsd     pgtype.Numeric
	LatencyMs    int32
	TtfbMs       pgtype.Int4
	CacheStatus  string
	Outcome      string
	Attempts     []byte
	CreatedAt    time.Time
}

func (q *Queries) InsertUsage(ctx context.Context, arg InsertUsageParams) error {
	_, err := q.db.Exec(ctx, insertUsage,
		arg.ID,
		arg.ApiKeyID,
		arg.RunID,
		arg.Policy,
		arg.Provider,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostUsd,
		arg.SavedUsd,
		arg.LatencyMs,
		arg.TtfbMs,
		arg.CacheStatus,
		arg.Outcome,
		arg.Attempts,
		arg.CreatedAt,
	)
	return err
}

const sumUsageDailySince = `-- name: SumUsageDailySince :one
SELECT COALESCE(SUM(cost_usd), 0)::numeric AS cost_usd
FROM usage_daily
WHERE api_key_id = $1 AND day >= $2
`

type SumUsageDailySinceParams struct {
	ApiKeyID uuid.UUID
	Since    pgtype.Date
}

func (q *Queries) SumUsageDailySince(ctx context.Context, arg SumUsageDailySinceParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumUsageDailySince, arg.ApiKeyID, arg.Since)
	var cost_usd pgtype.Numeric
	err := row.Scan(&cost_usd)
	return cost_usd, err
}

const upsertUsageDaily = `-- name: UpsertUsageDaily :exec
INSERT INTO usage_daily (api_key_id, day, model, requests, input_tokens, output_tokens, cost_usd, saved_usd, cache_hits)
VALUES ($1, $2, $3, 1, $4, $5, $6, $7, $8)
ON CONFLICT (api_key_id, day, model) DO UPDATE SET
  requests      = usage_daily.requests + 1,
  input_tokens  = usage_daily.input_tokens + EXCLUDED.input_tokens,
  output_tokens = usage_daily.output_tokens + EXCLUDED.output_tokens,
  cost_usd      = usage_daily.cost_usd + EXCLUDED.cost_usd,
  saved_usd     = usage_daily.saved_usd + EXCLUDED.saved_usd,
  cache_hits    = usage_daily.cache_hits + EXCLUDED.cache_hits
`

type UpsertUsageDailyParams struct {
	ApiKeyID     uuid.UUID
	Day          pgtype.Date
	Model        string
	InputTokens  int64
	OutputTokens int64
	CostUsd      pgtype.Numeric
	SavedUsd     pgtype.Numeric
	CacheHits    int64
}

func (q *Queries) UpsertUsageDaily(ctx context.Context, arg UpsertUsageDailyParams) error {
	_, err := q.db.Exec(ctx, upsertUsageDaily,
		arg.ApiKeyID,
		arg.Day,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostUsd,
		arg.SavedUsd,
		arg.CacheHits,
	)
	return err
}
