// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createUserIfMissing = `-- name: CreateUserIfMissing :one
INSERT INTO users (id, username, password_hash, role)
VALUES ($1, $2, $3, $4)
ON CONFLICT (username) DO NOTHING
RETURNING id
`

type CreateUserIfMissingParams struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	Role         string
}

func (q *Queries) CreateUserIfMissing(ctx context.Context, arg CreateUserIfMissingParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUserIfMissing,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, role, created_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const setUserPassword = `-- name: SetUserPassword :execrows
UPDATE users SET password_hash = $1, role = $2 WHERE username = $3
`

type SetUserPasswordParams struct {
	PasswordHash string
	Role         string
	Username     string
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserPassword, arg.PasswordHash, arg.Role, arg.Username)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
